---
# ==============================================================================
# Configurações Globais de Conexão HTTPAPI para Morpheus Core
# ==============================================================================
ansible_connection: httpapi
ansible_network_os: morpheus.core.morpheus
ansible_host: "morpheus.cec.dev.br"
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443

# Autenticação via API Access Token
ansible_morpheus_token: "c356423a-e931-40ca-a0de-6572ed4b9c2b"

# Variáveis gerais da integração Morpheus
morpheus_url: "https://morpheus.cec.dev.br"
morpheus_ssl_verify: false
morpheus_api_token: "c356423a-e931-40ca-a0de-6572ed4b9c2b"

morpheus_gcp_cloud_id: 24
morpheus_gcp_cloud_name: "loonar-gcp-terraform-ansible-samples"
morpheus_gcp_group_id: 5
morpheus_gcp_group_name: "GCP Loonar"

sample_instance_name: "vm-gcp-poc"
sample_cypher_key: "tfvars/gcp-create-vm-poc"
sample_keypair_name: "devopsvanilla-gcp-key"
