---
# ==============================================================================
# Inventário Estático para Conexão HTTPAPI com Morpheus Data
# ==============================================================================
# Define o host de controle do Morpheus utilizando o plugin httpapi da coleção.
# ==============================================================================

all:
  children:
    morpheus_servers:
      hosts:
        morpheus_appliance:
          ansible_host: "morpheus.cec.dev.br"
          ansible_connection: httpapi
          ansible_network_os: morpheus.core.morpheus
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_user: "POC\\administrator"
          ansible_password: "C0p132022!#hpe50POC"
          # ansible_httpapi_session_key: "SEU_API_TOKEN_AQUI"
          ansible_httpapi_port: 443

    morpheus_local:
      hosts:
        localhost:
          ansible_connection: local
